#!/usr/bin/php
<?php

//this script needs to be in the root directory of your app to work properly.
//Make sure that you have run `composer install` if the autoloader isn't working.
$root = __DIR__ . '/';

include($root . 'vendor/autoload.php');

use Neptune\Core\Config;
use Neptune\Core\Neptune;
use Neptune\Console\Application as ConsoleApplication;
use Neptune\Console\OutputFormatter;

use Symfony\Component\Console\Output\ConsoleOutput;

$output = new ConsoleOutput();
$output->setFormatter(new OutputFormatter());

//load neptune config
$config = 'config/neptune.php';

if(file_exists($config)) {
	$c = Config::load('neptune', $config);
} else {
	//write a warning if no neptune config is present and this isn't the setup command
	if(!isset($_SERVER['argv'][1]) || $_SERVER['argv'][1] !== 'setup') {
		$output->writeln('<error>No neptune config file found!</error>');
		$output->writeln('<error>You should run create:config to create config/neptune.php</error>');
		$output->writeln('<info>Creating temporary neptune config...</info>');
	}
	$c = Config::create('neptune', $config);
	$c->set('dir.neptune', $root . 'vendor/glynnforrest/neptune/');
}

$c->set('dir.root', $root);

$neptune = new Neptune($c);

//register all the application services
include('app/Application.php');
$app = new \Application();
$app->start($neptune);
$app->console($neptune, $output);

//off we go
$app = new ConsoleApplication($neptune, $c);

$app->run(null, $output);
